import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-6">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-600 text-white shadow-lg sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center py-4">
              <div className="text-xl font-semibold">
                <Link href="/" className="hover:text-gray-200 transition duration-300">Brand</Link>
              </div>
              <ul className="flex gap-6">
                <li>
                  <Link href="/" className="hover:text-gray-200 transition duration-300">Home</Link>
                </li>
                <li>
                  <Link href="/profile" className="hover:text-gray-200 transition duration-300">Profile</Link>
                </li>
                <li>
                  <Link href="/login" className="hover:text-gray-200 transition duration-300">Login</Link>
                </li>
                <li>
                  <Link href="/register" className="hover:text-gray-200 transition duration-300">Register</Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
